package com.notarius.shorturl.domain;

import static com.notarius.shorturl.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class UrlAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUrlAllPropertiesEquals(Url expected, Url actual) {
        assertUrlAutoGeneratedPropertiesEquals(expected, actual);
        assertUrlAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUrlAllUpdatablePropertiesEquals(Url expected, Url actual) {
        assertUrlUpdatableFieldsEquals(expected, actual);
        assertUrlUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUrlAutoGeneratedPropertiesEquals(Url expected, Url actual) {
        assertThat(expected)
            .as("Verify Url auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUrlUpdatableFieldsEquals(Url expected, Url actual) {
        assertThat(expected)
            .as("Verify Url relevant properties")
            .satisfies(e -> assertThat(e.getShortUrl()).as("check shortUrl").isEqualTo(actual.getShortUrl()))
            .satisfies(e -> assertThat(e.getFullUrl()).as("check fullUrl").isEqualTo(actual.getFullUrl()))
            .satisfies(
                e ->
                    assertThat(e.getCreationDateTime())
                        .as("check creationDateTime")
                        .usingComparator(zonedDataTimeSameInstant)
                        .isEqualTo(actual.getCreationDateTime())
            )
            .satisfies(
                e ->
                    assertThat(e.getExpirationDateTime())
                        .as("check expirationDateTime")
                        .usingComparator(zonedDataTimeSameInstant)
                        .isEqualTo(actual.getExpirationDateTime())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUrlUpdatableRelationshipsEquals(Url expected, Url actual) {}
}
